export const seedProducts = [
  // === SAREES ===
  {
    name: "Banarasi Silk Saree",
    slug: "banarasi-silk-saree",
    description:
      "A luxurious Banarasi silk saree with intricate gold zari work. Perfect for weddings, festivals, and special occasions. This saree features a rich pallu with traditional motifs and a matching blouse piece.",
    category: "Sarees",
    subcategory: "Silk",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    images: [
      "/images/saree-1.png",
      "/images/saree-2.jpg",
    ],
    sizes: ["Free Size"],
    colors: ["Red", "Maroon", "Gold"],
    stock: 25,
    sku: "SAR-0001",
    featured: true,
  },
  {
    name: "Printed Georgette Saree",
    slug: "printed-georgette-saree",
    description:
      "Lightweight georgette saree with beautiful floral prints. Ideal for daily wear and casual outings. Easy to drape and maintain with a soft, flowy texture.",
    category: "Sarees",
    subcategory: "Georgette",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    images: [
      "/images/saree-2.jpg",
      "/images/saree-1.png",
    ],
    sizes: ["Free Size"],
    colors: ["Blue", "Pink", "Green"],
    stock: 40,
    sku: "SAR-0002",
    featured: false,
  },
  {
    name: "Cotton Handloom Saree",
    slug: "cotton-handloom-saree",
    description:
      "Authentic handloom cotton saree with traditional border designs. Breathable and comfortable for everyday wear. Features a beautiful contrast border and pallu.",
    category: "Sarees",
    subcategory: "Cotton",
    price: 849,
    originalPrice: 1199,
    discount: 29,
    images: [
      "/images/saree-1.png",
    ],
    sizes: ["Free Size"],
    colors: ["White", "Cream", "Yellow"],
    stock: 30,
    sku: "SAR-0003",
    featured: false,
  },
  {
    name: "Chiffon Party Wear Saree",
    slug: "chiffon-party-wear-saree",
    description:
      "Elegant chiffon saree with sequin embellishments and shimmering border. Perfect for cocktail parties and evening events. Lightweight with a graceful drape.",
    category: "Sarees",
    subcategory: "Chiffon",
    price: 899,
    originalPrice: 1399,
    discount: 36,
    images: [
      "/images/saree-2.jpg",
    ],
    sizes: ["Free Size"],
    colors: ["Black", "Navy", "Wine"],
    stock: 20,
    sku: "SAR-0005",
    featured: false,
  },
  {
    name: "Tussar Silk Saree",
    slug: "tussar-silk-saree",
    description:
      "Natural tussar silk saree with hand-painted Madhubani art. A unique blend of traditional art and contemporary fashion. Each piece is slightly unique.",
    category: "Sarees",
    subcategory: "Silk",
    price: 949,
    originalPrice: 1399,
    discount: 32,
    images: [
      "/images/saree-1.png",
    ],
    sizes: ["Free Size"],
    colors: ["Beige", "Rust", "Olive"],
    stock: 12,
    sku: "SAR-0006",
    featured: false,
  },
  {
    name: "Daily Wear Linen Saree",
    slug: "daily-wear-linen-saree",
    description:
      "Premium linen saree with minimalist block print design. Ultra-comfortable for office and daily wear. Pre-washed for softness, gets better with every wash.",
    category: "Sarees",
    subcategory: "Linen",
    price: 749,
    originalPrice: 1099,
    discount: 32,
    images: [
      "/images/saree-1.png",
    ],
    sizes: ["Free Size"],
    colors: ["Grey", "Indigo", "Terracotta"],
    stock: 35,
    sku: "SAR-0008",
    featured: false,
  },

  // === KIDS WEAR ===
  {
    name: "Boys Casual T-Shirt & Shorts Set",
    slug: "boys-casual-tshirt-shorts-set",
    description:
      "Comfortable cotton t-shirt and shorts combo for boys. Soft breathable fabric with fun prints. Set includes 1 graphic tee and 1 matching shorts.",
    category: "Kids Wear",
    subcategory: "Boys",
    price: 649,
    originalPrice: 999,
    discount: 35,
    images: [
      "/images/kids.jpg",
    ],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Blue", "Green", "Grey"],
    stock: 45,
    sku: "KID-0002",
    featured: false,
  },
  {
    name: "Ethnic Kurta Pyjama Set for Boys",
    slug: "ethnic-kurta-pyjama-boys",
    description:
      "Traditional cotton kurta pyjama set for boys. Features embroidered neck and mirror work details. Ideal for festivals, weddings, and cultural events.",
    category: "Kids Wear",
    subcategory: "Boys",
    price: 949,
    originalPrice: 1399,
    discount: 32,
    images: [
      "/images/kids.jpg",
    ],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["White", "Cream", "Yellow"],
    stock: 25,
    sku: "KID-0003",
    featured: false,
  },
  {
    name: "Baby Romper Set (3 Pack)",
    slug: "baby-romper-set-3pack",
    description:
      "Set of 3 soft cotton rompers for babies (0-2 years). Snap buttons for easy changing, pre-shrunk fabric. Pack includes 3 different color combinations.",
    category: "Kids Wear",
    subcategory: "Baby",
    price: 749,
    originalPrice: 1099,
    discount: 32,
    images: [
      "/images/kids.jpg",
    ],
    sizes: ["0-3M", "3-6M", "6-12M", "12-24M"],
    colors: ["Multicolor"],
    stock: 50,
    sku: "KID-0005",
    featured: false,
  },
  {
    name: "Kids Denim Jacket",
    slug: "kids-denim-jacket",
    description:
      "Trendy denim jacket for kids with soft inner lining. Classic trucker style with button closure. A versatile layering piece for all seasons.",
    category: "Kids Wear",
    subcategory: "Boys",
    price: 949,
    originalPrice: 1399,
    discount: 32,
    images: [
      "/images/kids.jpg",
    ],
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Blue", "Dark Blue"],
    stock: 22,
    sku: "KID-0006",
    featured: false,
  },

  // === JEWELLERY ===
  {
    name: "Kundan Necklace Set",
    slug: "kundan-necklace-set",
    description:
      "Exquisite Kundan necklace set with matching earrings and maang tikka. Features American diamonds and detailed meenakari work. Perfect for weddings and festive occasions.",
    category: "Jewellery",
    subcategory: "Necklace Sets",
    price: 999,
    originalPrice: 1499,
    discount: 33,
    images: [
      "/images/jewellery-1.jpg",
      "/images/jewellery-2.jpg",
    ],
    sizes: ["One Size"],
    colors: ["Gold", "Silver"],
    stock: 30,
    sku: "JWL-0001",
    featured: true,
  },
  {
    name: "Jhumka Earrings",
    slug: "jhumka-earrings",
    description:
      "Traditional gold-tone Jhumka earrings with pearl drops. Lightweight and comfortable for all-day wear. A timeless classic that pairs with any ethnic outfit.",
    category: "Jewellery",
    subcategory: "Earrings",
    price: 649,
    originalPrice: 1099,
    discount: 41,
    images: [
      "/images/jewellery-2.jpg",
    ],
    sizes: ["One Size"],
    colors: ["Gold", "Antique Gold"],
    stock: 50,
    sku: "JWL-0002",
    featured: false,
  },
  {
    name: "Pearl String Set",
    slug: "pearl-string-set",
    description:
      "Elegant multi-strand pearl necklace set with gold-tone clasp. Includes 3-layer necklace and drop earrings. Sophisticated and graceful for formal occasions.",
    category: "Jewellery",
    subcategory: "Necklace Sets",
    price: 1099,
    originalPrice: 1499,
    discount: 27,
    images: [
      "/images/jewellery-1.jpg",
    ],
    sizes: ["One Size"],
    colors: ["White", "Cream"],
    stock: 25,
    sku: "JWL-0004",
    featured: false,
  },
  {
    name: "Bridal Polki Set",
    slug: "bridal-polki-set",
    description:
      "Stunning bridal Polki jewellery set with uncut diamonds and pearl detailing. Includes rani haar, choker, earrings, maang tikka, and bangles. A complete bridal collection.",
    category: "Jewellery",
    subcategory: "Bridal",
    price: 1199,
    originalPrice: 1499,
    discount: 20,
    images: [
      "/images/jewellery-2.jpg",
    ],
    sizes: ["One Size"],
    colors: ["Gold"],
    stock: 8,
    sku: "JWL-0005",
    featured: true,
  },
  {
    name: "Daily Wear Oxidised Set",
    slug: "daily-wear-oxidised-set",
    description:
      "Trendy oxidised silver jewellery set for everyday styling. Includes long necklace and jhumka earrings. Lightweight, versatile, and perfect for Indo-western looks.",
    category: "Jewellery",
    subcategory: "Casual",
    price: 549,
    originalPrice: 849,
    discount: 35,
    images: [
      "/images/jewellery-1.jpg",
    ],
    sizes: ["One Size"],
    colors: ["Silver", "Oxidised"],
    stock: 40,
    sku: "JWL-0006",
    featured: false,
  },

  // === BANGLES ===
  {
    name: "Gold-Tone Classic Bangles Set",
    slug: "gold-tone-classic-bangles-set",
    description:
      "Set of 6 gold-tone bangles with traditional etched design. Durable alloy with anti-tarnish coating. Perfect for daily wear and festive occasions.",
    category: "Bangles",
    subcategory: "Gold-Tone",
    price: 649,
    originalPrice: 1099,
    discount: 41,
    images: [
      "/images/bangles.png",
    ],
    sizes: ["2.4", "2.6", "2.8"],
    colors: ["Gold"],
    stock: 60,
    sku: "BNG-0001",
    featured: true,
  },
  {
    name: "Glass Wedding Bangles Set",
    slug: "glass-wedding-bangles-set",
    description:
      "Traditional glass bangles set for weddings. Set of 12 bangles in matching colors with gold lace detailing. A must-have for bridal and festive celebrations.",
    category: "Bangles",
    subcategory: "Glass",
    price: 449,
    originalPrice: 749,
    discount: 40,
    images: [
      "/images/bangles.png",
    ],
    sizes: ["2.4", "2.6"],
    colors: ["Red", "Green", "Yellow"],
    stock: 45,
    sku: "BNG-0002",
    featured: false,
  },
  {
    name: "Temple Design Kangan",
    slug: "temple-design-kangan",
    description:
      "Intricately designed temple kangan with Goddess Lakshmi motif. Gold-plated brass with meenakari work. A statement piece for traditional occasions.",
    category: "Bangles",
    subcategory: "Kangan",
    price: 1099,
    originalPrice: 1499,
    discount: 27,
    images: [
      "/images/bangles.png",
    ],
    sizes: ["2.4", "2.6", "2.8"],
    colors: ["Gold"],
    stock: 20,
    sku: "BNG-0003",
    featured: false,
  },
  {
    name: "Adjustable Brass Bangle Set",
    slug: "adjustable-brass-bangle-set",
    description:
      "Set of 4 adjustable brass bangles with hammered texture. Fits most wrist sizes. Bohemian and contemporary design that goes with both ethnic and western outfits.",
    category: "Bangles",
    subcategory: "Brass",
    price: 549,
    originalPrice: 849,
    discount: 35,
    images: [
      "/images/bangles.png",
    ],
    sizes: ["Adjustable"],
    colors: ["Antique Gold", "Silver"],
    stock: 35,
    sku: "BNG-0004",
    featured: false,
  },

  // === NIGHT SUIT ===
  {
    name: "Cotton Night Suit",
    slug: "cotton-night-suit",
    description:
      "A soft cotton-knit night suit with a relaxed top and matching pants. Breathable fabric with an elastic waistband for all-night comfort and easy movement.",
    category: "Night Suit",
    subcategory: "Night Suit",
    price: 699,
    originalPrice: 999,
    discount: 30,
    images: [
      "/images/nightsuit.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Mint", "Lavender"],
    stock: 45,
    sku: "NGS-0001",
    featured: false,
  },
  {
    name: "Silk Satin Night Dress",
    slug: "silk-satin-night-dress",
    description:
      "Luxurious silk-satin night dress with lace trim and adjustable straps. A relaxed, breathable fit with a soft sheen â€” perfect for a comfortable night's sleep.",
    category: "Night Suit",
    subcategory: "Night Gown",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    images: [
      "/images/nightsuit.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Burgundy", "Navy", "Black"],
    stock: 30,
    sku: "NGS-0002",
    featured: true,
  },
  {
    name: "Cozy Fleece Night Suit",
    slug: "cozy-fleece-night-suit",
    description:
      "A warm fleece-lined night suit with a pullover top and jogger pants. Soft brushed inner for extra warmth â€” ideal for cooler evenings and winter nights.",
    category: "Night Suit",
    subcategory: "Night Suit",
    price: 999,
    originalPrice: 1399,
    discount: 29,
    images: [
      "/images/nightsuit.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Teal", "Rose"],
    stock: 25,
    sku: "NGS-0003",
    featured: false,
  },
  {
    name: "Three-Piece Night Suit Set",
    slug: "three-piece-night-suit-set",
    description:
      "A stylish three-piece night suit with a short kurti top, matching pants and dupatta. Lightweight rayon with printed accents for a breezy, comfortable sleep.",
    category: "Night Suit",
    subcategory: "Night Suit",
    price: 1099,
    originalPrice: 1499,
    discount: 27,
    images: [
      "/images/nightsuit.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Peach", "Sky Blue", "Mustard"],
    stock: 20,
    sku: "NGS-0004",
    featured: false,
  },
  // === KURTI ===
  {
    name: "Anarkali Kurti with Palazzo",
    slug: "anarkali-kurti-palazzo",
    description:
      "Flowy Anarkali kurti paired with a matching palazzo for an effortless ethnic look. Feather-light georgette with delicate embroidery on the yoke and a flared silhouette that flatters every body type.",
    category: "Kurti",
    subcategory: "Kurti",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    images: [
      "/images/kurti.jpg",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Maroon", "Teal", "Mustard"],
    stock: 35,
    sku: "KRT-0001",
    featured: true,
  },
  {
    name: "Straight-Cut Cotton Kurti",
    slug: "straight-cut-cotton-kurti",
    description:
      "A breezy straight-cut kurti in soft pure cotton with a mandarin collar and side slits. Breathable and wrinkle-resistant Ã¢â‚¬â€ your go-to for daily wear and office.",
    category: "Kurti",
    subcategory: "Kurti",
    price: 749,
    originalPrice: 1199,
    discount: 38,
    images: [
      "/images/blouse.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Blue"],
    stock: 50,
    sku: "KRT-0002",
    featured: false,
  },
  {
    name: "Silk Blend Blouse",
    slug: "silk-blend-blouse",
    description:
      "An elegant silk-blend blouse with a graceful bow neck and cap sleeves. Luxe sheen with a smooth finish Ã¢â‚¬â€ ideal for pairing with sarees or for festive evenings.",
    category: "Blouse",
    subcategory: "Blouse",
    price: 899,
    originalPrice: 1399,
    discount: 36,
    images: [
      "/images/kurti.jpg",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gold", "Emerald", "Royal Blue"],
    stock: 28,
    sku: "KRT-0004",
    featured: false,
  },
  {
    name: "Embroidered Sleeveless Blouse",
    slug: "embroidered-sleeveless-blouse",
    description:
      "Hand-embroidered sleeveless blouse with a keyhole back and satin piping. Pre-stitched and ready to wear, it pairs beautifully with your favourite saree.",
    category: "Blouse",
    subcategory: "Blouse",
    price: 849,
    originalPrice: 1299,
    discount: 35,
    images: [
      "/images/blouse.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Burgundy"],
    stock: 32,
    sku: "KRT-0005",
    featured: false,
  },
  // === HAND BAGS ===
  {
    name: "Classic Leather Handbag",
    slug: "classic-leather-handbag",
    description:
      "A timeless statement handbag in premium faux leather with a structured silhouette. Spacious main compartment and an easy top-zip closure â€” perfect for work or evenings out.",
    category: "Hand Bags",
    subcategory: "Handbags",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    images: [
      "/images/handbag.png",
    ],
    sizes: ["Free Size"],
    colors: ["Black", "Tan", "Brown"],
    stock: 18,
    sku: "HAN-0001",
    featured: true,
  },
  {
    name: "Everyday Tote Bag",
    slug: "everyday-tote-bag",
    description:
      "A roomy canvas-lined tote that carries everything you need with ease. Wide handles, an interior pocket, and a relaxed drape make it an everyday essential.",
    category: "Hand Bags",
    subcategory: "Totes",
    price: 949,
    originalPrice: 1299,
    discount: 27,
    images: [
      "/images/handbag.png",
    ],
    sizes: ["Free Size"],
    colors: ["Beige", "Olive", "Black"],
    stock: 24,
    sku: "HAN-0002",
    featured: false,
  },
  {
    name: "Quilted Sling Bag",
    slug: "quilted-sling-bag",
    description:
      "A chic quilted sling with a gold-tone chain strap and secure closure. Compact yet stylish, it adds a polished touch to casual and festive outfits alike.",
    category: "Hand Bags",
    subcategory: "Sling Bags",
    price: 799,
    originalPrice: 1099,
    discount: 27,
    images: [
      "/images/handbag.png",
    ],
    sizes: ["Free Size"],
    colors: ["White", "Black", "Pink"],
    stock: 30,
    sku: "HAN-0003",
    featured: false,
  },
  {
    name: "Evening Clutch Purse",
    slug: "evening-clutch-purse",
    description:
      "A compact clutch with a sleek finish and a detachable wristlet strap. Designed to hold your phone and essentials for parties, weddings, and special occasions.",
    category: "Hand Bags",
    subcategory: "Clutches",
    price: 699,
    originalPrice: 999,
    discount: 30,
    images: [
      "/images/handbag.png",
    ],
    sizes: ["Free Size"],
    colors: ["Gold", "Black", "Red"],
    stock: 35,
    sku: "HAN-0004",
    featured: false,
  },
  {
    name: "Structured Shoulder Bag",
    slug: "structured-shoulder-bag",
    description:
      "A neat structured shoulder bag with a top handle and detachable long strap. Clean lines and a roomy interior make it a versatile wardrobe staple.",
    category: "Hand Bags",
    subcategory: "Shoulder Bags",
    price: 1149,
    originalPrice: 1399,
    discount: 18,
    images: [
      "/images/handbag.png",
    ],
    sizes: ["Free Size"],
    colors: ["Brown", "Black", "Camel"],
    stock: 20,
    sku: "HAN-0005",
    featured: false,
  },
];
